name: balochi_tutor
description: "teach the balochi language"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  another_flushbar: ^1.12.32
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2
  hive: ^2.2.3
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  image_picker: ^1.2.0
  dropdown_search: ^6.0.2
  fl_chart: ^1.0.0
  google_fonts: ^6.3.0
  flutter_switch: ^0.3.2
  file_picker: ^10.3.2
  flutter_spinkit: ^5.2.2
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  country_picker: ^2.0.27
  screen_protector: ^1.4.4
  dio:
  firebase_messaging: ^16.0.4
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.2
  flutter_tts: ^4.2.3
  translator: ^1.0.4+1
  firebase_core: ^4.2.1
  flutter_local_notifications: ^19.5.0
  device_info_plus: ^12.2.0
  flutter_html:



dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/balochi_logo.png"
  adaptive_icon_foreground: "assets/icons/balochi_logo.png"
  adaptive_icon_padding: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
